name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'develop'

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Cache Python dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-cache-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: python-cache-${{ runner.os }}-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

  test:
    name: Run Tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-cache-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Run Tests
        run: pytest -v tests/

  lint:
    name: Lint Code
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-cache-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Run Lint
        run: pylint envcloak/
        continue-on-error: true

  security-check:
    name: Security Check
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-cache-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Run Bandit
        run: bandit -v -r envcloak/

  build-and-deploy:
    name: Build and Deploy to PyPI
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - security-check
    if: github.ref == 'refs/heads/main'  # Only run on the main branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-cache-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build Package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*